import assert from 'node:assert/strict';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, relative } from 'node:path';
import test from 'node:test';

const root = fileURLToPath(new URL('..', import.meta.url));
const textExtensions = new Set(['.css', '.html', '.js', '.json', '.md', '.mjs']);
const ignoredDirectories = new Set(['.git', 'vendor']);

function walk(directory) {
  const paths = [];
  for (const entry of readdirSync(directory)) {
    if (ignoredDirectories.has(entry)) continue;
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) paths.push(...walk(path));
    else if ([...textExtensions].some(extension => entry.endsWith(extension))) paths.push(path);
  }
  return paths;
}

test('deployed first-party sources contain no assistant or build-session residue', () => {
  const files = [join(root, 'README.md'), ...walk(join(root, 'public'))];
  const banned = [
    /\b(?:ChatGPT|Claude|Codex|OpenAI)\b/i,
    /\bagents?'?\s+write_file\b/i,
    /\bwrite_file\s+tool\b/i,
    /\bas an AI\b/i,
    /\bAI[- ]generated\b/i,
    /\bgenerated by AI\b/i,
    /\bsay the word and I['’]ll\b/i,
    /\bmy proposals\b/i,
    /uploads\/planner_decoded\.html/i
  ];

  const failures = [];
  for (const path of files) {
    const content = readFileSync(path, 'utf8');
    for (const pattern of banned) {
      if (pattern.test(content)) failures.push(`${relative(root, path)} matches ${pattern}`);
    }
  }
  assert.deepEqual(failures, []);
});
